### PR TITLE
Contact Updated

### PR DESCRIPTION
**Pull request by hunainabbas26**

### CODE REVIEW

**Comment by hunainabbas26** [comment]
Contact Info Updated

**Comment by hunainabbas26** [comment]
Contact Number Removed

**Comment by ydmk** [comment]
It seems only the contact number was removed? any other changes?

**Comment by hunainabbas26** [comment]
Yes YMK we only update the Contact Details. nothing else.

**Comment by ydmk** [comment]
There's no updating, you've just removed it. Is that the desired behavior?

**Review by ydmk — APPROVED** [review]

**Pull request merged**
